spring:
  datasource:
    url: {{ .Values.db.url }}/auditdb
    username: '{{ .Values.db.username }}'
    password: '{{ .Values.db.password }}'
logging:
    level:
      com.opsmx.auditservice: INFO
feign:
  client:
    config:
      default:
        connectTimeout: 100000
        readTimeout: 100000
        loggerLevel: basic
    platformservice:
      name: platformservice
      url: http://oes-platform:8095
    auditclientservice:
      name: auditclientservice
      url: http://oes-audit-client:8098
    oes:
      url: http://oes-sapor:8085
    autopilot:
      url: http://oes-autopilot:8090
    visibilityservice:
      url: http://oes-visibility:8096
    dashboard:
      url: http://oes-dashboard:8094
