{{- if .Values.global.stormdriver }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stormdriver-rw
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: stormdriver-rw
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: stormdriver-rw
    spec:
      containers:
        - image: quay.io/opsmxpublic/stormdriver:v1
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 8090
            initialDelaySeconds: 3
            periodSeconds: 3
          name: stormdriver-container
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /app/config/stormdriver.yaml
              name: stormdriver-config-rw
              readOnly: true
              subPath: stormdriver.yaml
      volumes:
        - configMap:
            defaultMode: 420
            name: stormdriver-config-rw
          name: stormdriver-config-rw
{{- end }}
