apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "spinnaker.fullname" . }}-halyard-config
  labels:
{{ include "spinnaker.standard-labels" . | indent 4 }}
data:
  install.sh: |
    #!/bin/bash

    # Wait for the Hal daemon to be ready
    export DAEMON_ENDPOINT='curl http://{{ .Release.Name }}-spinnaker-halyard:8064/health'
    export HAL_COMMAND="$DAEMON_ENDPOINT"
    until $HAL_COMMAND ; do sleep 10 ; done

    {{- if not .Values.gitopsHalyard.enabled }}

    bash -xe /opt/halyard/scripts/config.sh

    {{- if .Values.halyard.additionalScripts.enabled }}
    bash /opt/halyard/additional/{{ .Values.halyard.additionalScripts.configMapKey }}
    {{- end }}

    {{- if  and .Values.halyard.additionalScripts.create .Values.halyard.additionalScripts.data }}
    {{- range $index, $script := .Values.halyard.additionalScripts.data }}
    bash -xe /opt/halyard/additionalScripts/{{ $index }}
    {{- end }} # Range
    {{- end }} # if-additionalScipts
    {{- else if .Values.gitopsHalyard.mTLS.enabled }}
    # Create secrets and certs necessary for mTLS
    cd /tmp/
    kubectl get secret mtlscerts-pkcs12 -o jsonpath='{.data.ca\.crt}'| base64 -d > ca.crt
    keytool -importcert -keystore  cacerts -alias ca -file ca.crt -storepass changeit -noprompt
    kubectl create secret generic cacerts --from-file cacerts
    cd -
    {{- end }} # end of if not gitops

    {{- if .Values.global.enableCentralMonitoring }}
    #Enable prometheus
    $HAL_COMMAND config metric-stores prometheus enable
    {{- end }}

    # This is performed by post-start script in halyard pod
    # in case gitopsHalyard is enabled
    {{- if not .Values.gitopsHalyard.enabled }}
    $HAL_COMMAND deploy apply
    {{- end }}

    {{- if .Values.halyard.additionalInstallParameters }} \
      {{- .Values.halyard.additionalInstallParameters | join " \\\n" | nindent 6 }}
    {{- end }}
  clean.sh: |
    export HAL_COMMAND='hal --daemon-endpoint http://{{ template "spinnaker.fullname" . }}-halyard:8064'
    if $HAL_COMMAND --ready; then
      $HAL_COMMAND deploy clean -q
    fi
  config.sh: |
    # Spinnaker version
    {{ if .Values.halyard.bom }}
    $HAL_COMMAND config version edit --version local:{{ .Values.halyard.spinnakerVersion }}
    {{ else }}
    $HAL_COMMAND config version edit --version {{ .Values.halyard.spinnakerVersion }}
    {{ end }}

    # Storage
    {{ if .Values.global.minio.enabled }}
    echo {{ .Values.global.minio.secretKey }} | $HAL_COMMAND config storage s3 edit \
        --endpoint http://{{ .Release.Name }}-minio:9000 \
        --access-key-id {{ .Values.global.minio.accessKey }} \
        --secret-access-key --bucket {{ .Values.global.minio.defaultBucket.name }} \
        --path-style-access true
    $HAL_COMMAND config storage edit --type s3
    {{ end }}
    {{ if .Values.s3.enabled }}
    {{- if .Values.s3.secretKey -}} cat /opt/s3/secretKey | {{- end }} $HAL_COMMAND config storage s3 edit \
      --bucket {{ .Values.s3.bucket }} \
      {{- if .Values.s3.rootFolder }}
      --root-folder {{ .Values.s3.rootFolder }} \
      {{- end }}
      {{- if .Values.s3.region }}
      --region {{ .Values.s3.region }} \
      {{- end }}
      {{- if .Values.s3.endpoint }}
      --endpoint {{ .Values.s3.endpoint }} \
      {{- end }}
      {{- if .Values.s3.assumeRole }}
      --assume-role {{ .Values.s3.assumeRole }} \
      {{- end }}
      {{- if .Values.s3.accessKey }}
      --access-key-id "$(cat /opt/s3/accessKey)" \
      {{- end }}
      {{- if .Values.s3.secretKey }}
      --secret-access-key \
      {{- end }}
      {{- range .Values.s3.extraArgs }}
      {{- . }} \
      {{- end }}

    $HAL_COMMAND config storage edit --type s3
    {{ end }}
    {{ if .Values.gcs.enabled }}
    $HAL_COMMAND config storage gcs edit --project {{ .Values.gcs.project }} --json-path /opt/gcs/key.json --bucket {{ .Values.gcs.bucket }}
    $HAL_COMMAND config storage edit --type gcs
    {{ end }}
    {{ if .Values.azs.enabled }}
    $HAL_COMMAND config storage azs edit --storage-account-name {{ .Values.azs.storageAccountName }} \
      {{- if .Values.azs.containerName }}
      --storage-container-name {{ .Values.azs.containerName }} \
      {{- end }}
      --storage-account-key "{{ .Values.azs.accessKey }}"
    $HAL_COMMAND config storage edit --type azs
    {{ end }}

    # Docker Registry
    $HAL_COMMAND config provider docker-registry enable
    {{- range $index, $registry := .Values.dockerRegistries }}

    if $HAL_COMMAND config provider docker-registry account get {{ $registry.name }}; then
      PROVIDER_COMMAND='edit'
    else
      PROVIDER_COMMAND='add'
    fi

    $HAL_COMMAND config provider docker-registry account $PROVIDER_COMMAND {{ $registry.name }} --address {{ $registry.address }} \
      {{ if $registry.username -}} --username {{ $registry.username }} \
      {{ if $registry.passwordCommand -}} --password-command "{{ $registry.passwordCommand }}"{{ else -}} --password-file /opt/registry/passwords/{{ $registry.name }}{{- end }} \
      {{ if $registry.email -}} --email {{ $registry.email }}{{- end -}}{{- end }} \
      {{ if $registry.repositories -}} --repositories {{ range $index, $repository := $registry.repositories }}{{if $index}},{{end}}{{- $repository }}{{- end }}{{- end }}

    {{- end }}

    $HAL_COMMAND config provider kubernetes enable
    {{- range $index, $context := .Values.kubeConfig.contexts }}

    if $HAL_COMMAND config provider kubernetes account get {{ $context }}; then
      PROVIDER_COMMAND='edit'
    else
      PROVIDER_COMMAND='add'
    fi

    $HAL_COMMAND config provider kubernetes account $PROVIDER_COMMAND {{ $context }} --docker-registries dockerhub \
                --context {{ $context }} {{ if not $.Values.kubeConfig.enabled }}--service-account true{{ end }} \
                {{ if $.Values.kubeConfig.enabled }}--kubeconfig-file {{ template "spinnaker.kubeconfig" $ }}{{ end }} \
                {{ if $.Values.kubeConfig.onlySpinnakerManaged.enabled }}--only-spinnaker-managed true{{ end }} \
                {{ if not $.Values.kubeConfig.checkPermissionsOnStartup }}--check-permissions-on-startup false{{ end }} \
                {{ if $.Values.kubeConfig.nameSpaces }}--namespaces={{ template "nameSpaces" $ }}{{ end }} \
                {{ if not $.Values.kubeConfig.nameSpaces }}--omit-namespaces={{ template "omittedNameSpaces" $ }}{{ end }} \
                {{ if $.Values.kubeConfig.omittedKinds }}--omit-kinds={{ template "omittedKinds" $ }}{{ end }} \
                {{ if $.Values.kubeConfig.kinds }}--kinds={{ template "k8sKinds" $ }}{{ end }} \
                {{ if $.Values.kubeConfig.liveManifestCalls }}--live-manifest-calls true{{ end }} \
                --provider-version v2
    {{- end }}
    $HAL_COMMAND config deploy edit --account-name {{ .Values.kubeConfig.deploymentContext }} --type distributed \
                           --location {{ .Release.Namespace }}
    {{- if .Values.enableHA }}
    $HAL_COMMAND config deploy ha clouddriver enable
    $HAL_COMMAND config deploy ha echo enable
    {{- end }}

    # Enable Authentication by default
    {{- if .Values.global.ldap.enabled }}
    {{- if .Values.global.installOpenLdap }}
    $HAL_COMMAND config security authn ldap edit --url ldap://{{ .Release.Name }}-openldap:389 --user-dn-pattern  'cn={0},dc=example,dc=org'
    {{- else }}
    $HAL_COMMAND config security authn ldap edit --url {{ .Values.global.ldap.url }} --user-dn-pattern  {{ .Values.global.ldap.userDnPattern }}
    $HAL_COMMAND config security authn ldap edit --manager-dn {{ .Values.global.ldap.managerDn }} --manager-password {{ .Values.global.ldap.managerPassword }}
    {{- end }}
    $HAL_COMMAND config security authn ldap enable
    {{- else }}
    $HAL_COMMAND config security authn ldap disable
    {{- end }}

    # Enable Authorization
    {{- if .Values.global.commonGate.spinnakerRBAC }}
    $HAL_COMMAND config security authz enable
    {{- else }}
    $HAL_COMMAND config security authz disable
    {{- end }}


    # Use Deck to route to Gate
    {{- if not .Values.gitopsHalyard.enabled }}
    # Configure override urls in halyard config
    {{- if .Values.global.autoConfiguration.enabled }}
    DECK_LB_IP=$(kubectl get svc spin-deck-lb -o jsonpath="{.status.loadBalancer.ingress[].ip}")
    if [ ! -z "$DECK_LB_IP" ];
    then
      $HAL_COMMAND config security ui edit --no-validate --override-base-url {{ .Values.global.spinDeck.protocol }}://$DECK_LB_IP:9000
    fi
    {{- else if .Values.global.spinDeck.port }}
    $HAL_COMMAND config security ui edit --no-validate --override-base-url {{ .Values.global.spinDeck.protocol }}://{{ .Values.global.spinDeck.host }}:{{ .Values.global.spinDeck.port }}
    {{- else }}
    $HAL_COMMAND config security ui edit --no-validate --override-base-url {{ .Values.global.spinDeck.protocol }}://{{ .Values.global.spinDeck.host }}
    {{- end }}

    {{- if .Values.global.autoConfiguration.enabled }}
    {{- if .Values.global.commonGate.enabled }}
    GATE_LB_IP=$(kubectl get svc oes-gate -o jsonpath="{.status.loadBalancer.ingress[].ip}")
    {{- else }}
    GATE_LB_IP=$(kubectl get svc spin-gate-lb -o jsonpath="{.status.loadBalancer.ingress[].ip}")
    {{- end }}
    if [ ! -z "$GATE_LB_IP" ];
    then
      $HAL_COMMAND config security api edit --no-validate --override-base-url {{ .Values.global.spinGate.protocol }}://$GATE_LB_IP:8084
    fi
    {{- else if and (.Values.global.spinGate.port) (not .Values.global.commonGate.enabled) }}
    $HAL_COMMAND config security api edit --no-validate --override-base-url {{ .Values.global.spinGate.protocol }}://{{ .Values.global.spinGate.host }}:{{ .Values.global.spinGate.port }}
    {{- else if (not .Values.global.commonGate.enabled) }}
    $HAL_COMMAND config security api edit --no-validate --override-base-url {{ .Values.global.spinGate.protocol }}://{{ .Values.global.spinGate.host }}
    {{- else if and (.Values.global.commonGate.enabled) (.Values.global.oesGate.port) }}
    $HAL_COMMAND config security api edit --no-validate --override-base-url {{ .Values.global.oesGate.protocol }}://{{ .Values.global.oesGate.host }}:{{ .Values.global.oesGate.port }}
    {{- else if (.Values.global.commonGate.enabled) }}
    $HAL_COMMAND config security api edit --no-validate --override-base-url {{ .Values.global.oesGate.protocol }}://{{ .Values.global.oesGate.host }}
    {{- end }}
    {{- end }}
    {{- range $index, $feature := .Values.spinnakerFeatureFlags }}
    $HAL_COMMAND config features edit --{{ $feature }} true
    {{- end }}
