{{ if or (eq .Values.installationMode "OES-AP")  (eq .Values.installationMode "EASY") }}
apiVersion: v1
data:
{{- if and (.Values.installSpinnaker) (not .Values.global.gitea.enabled)  }}
{{ (tpl (.Files.Glob "config/oes-ui/nginx.conf").AsConfig . ) | indent 2 }}
{{- else }}
{{- if and (.Values.global.gitea.enabled) (.Values.installSpinnaker ) }}
{{ (tpl (.Files.Glob "config/oes-ui/nginx-quick-install.conf").AsConfig . ) | indent 2 }}
{{- else }}
{{ (tpl (.Files.Glob "config/oes-ui/nginx-ap-only.conf").AsConfig . ) | indent 2 }}
{{- end }}
{{- end }}

kind: ConfigMap
metadata:
  name: oes-ui-nginxconf
  labels:
    app: oes
    component: ui
{{ include "oes.standard-labels" . | indent 4 }}
{{ end }}
