{{- if and (or (eq .Values.installationMode "OES-AP")  (eq .Values.installationMode "EASY")) (.Values.forwarder.enabled) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-controller-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-controller-secret
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get","list","create","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-controller-secret
subjects:
- kind: ServiceAccount
  name: create-controller-secret
roleRef:
  kind: Role
  name: create-controller-secret
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-controller-secret
spec:
 template:
    spec:
       containers:
       - name: create-secret-container
         image: {{ .Values.global.customImages.registry }}/create-secret:v10
         env:
         - name: NAMESPACE
           valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
         args: 
         - "$(NAMESPACE)" 
       restartPolicy: Never
       serviceAccount: create-controller-secret
{{- end -}}


