{{- if or (eq .Values.installationMode "OES-AP")  (eq .Values.installationMode "EASY") }}
{{- if and .Values.forwarder.enabled .Release.IsInstall }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-controller-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-controller-secret
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get","list","create","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-controller-secret
subjects:
- kind: ServiceAccount
  name: create-controller-secret
roleRef:
  kind: Role
  name: create-controller-secret
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-controller-secret
spec:
 template:
    spec:
       containers:
       - name: create-secret-container
         image: {{ template "createcontroller.image" .}}
         env:
         - name: NAMESPACE
           valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
         args:
         - "$(NAMESPACE)"
       {{- if .Values.imagePullSecret }}
       imagePullSecrets:
       - name: {{ .Values.imagePullSecret }}
       {{- end }} 
       restartPolicy: Never
       {{- if .Values.global.nodeSelector }}
       nodeSelector:
{{ toYaml .Values.global.nodeSelector | indent 8 }}
       {{- end }}
       {{- if .Values.global.affinity }}
       affinity:
{{ toYaml .Values.global.affinity | indent 8 }}
       {{- end }}
       {{- if .Values.global.tolerations }}
       tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
       {{- end }}
       serviceAccount: create-controller-secret
{{- end }}
{{- end }}


