{{- if and (or (eq .Values.installationMode "OES-AP")  (eq .Values.installationMode "EASY")) (.Values.forwarder.enabled) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: opsmx-controller-controller1
  labels:
    agent.opsmx.com/name: controller1
    agent.opsmx.com/role: controller
{{ include "oes.standard-labels" . | indent 4 }}
data:
  configFile: |
    serviceHostname: opsmx-controller-controller1
    agentHostname: {{ .Values.forwarder.externalName }}
    remoteCommandHostname: {{ .Values.forwarder.externalName }}
    controlHostname: opsmx-controller-controller1
    #agentAdvertisePort: "443"
    serviceAuth:
      currentKeyName: "public.pem"
      headerMutationKeyName: "public.pem"
    services:
      outgoingServices:
        - name: front50
          type: front50
          enabled: true
          config:
            url: http://spin-front50:8080
        - name: fiat
          type: fiat
          enabled: true
          config:
            url: http://spin-fiat:7003
      incomingServices:  # This part is to be automated in the next version. For now, the agent MUST be called opsmx-agent
        - name: agent-clouddriver
          serviceType: clouddriver
          port: 7002
          useHTTP: true
          destination: opsmx-agent
          destinationService: agent-clouddriver

{{- end -}}
