{{- if (eq .Values.installationMode "OES") -}}
{{- if .Values.forwarder.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: opsmx-controller-controller1-interproc
  labels:
    agent.opsmx.com/name: controller1
    agent.opsmx.com/role: controller
{{ include "oes.standard-labels" . | indent 4 }}
spec:
  selector:
    app: opsmx-controller-controller1
  type: {{ .Values.forwarder.agent.serviceType }}
  ports:
  - name: agent-grpc
    port: 9001
    targetPort: agent-grpc
{{- end -}}
{{- end -}}
