apiVersion: v2
name: oes
version: 3.10.2
appVersion: 3.10.1
description: ISD 3.10.1 with log4j security fix and additional enhancements
icon: https://raw.githubusercontent.com/OpsMx/enterprise-spinnaker/master/img/opsmx.png
maintainers:
- email: srinivas@opsmx.io
  name: ksrinimba
keywords:
  - OpsMx
  - OES
  - Autopilot
home: https://www.opsmx.com/
dependencies:
  - name: openldap
    version: 1.2.3
    condition: global.installOpenLdap
  - name: spinnaker
    version: 2.2.3
    condition: installSpinnaker
  - name: minio
    version: 8.0.9
    condition: global.minio.enabled
  - name: redis
    version: 10.5.3
    condition: installRedis
  - name: elasticsearch
    version: 7.5.0
    condition: enableCentralLogging
  - name: kibana
    version: 7.5.0
    condition: enableCentralLogging
  - name: fluent-bit
    version: 2.8.2
    condition: enableCentralLogging
  - name: prometheus
    version: 11.16.2
    condition: spinnaker.enableCentralMonitoring
