## Quay container image registry credentials to create imagePullSecret
##
imageCredentials:
  username: raghuramopsmx  # Quay username
  password: Kubernetes@2019 # Quay password
  email: info@opsmx.com   # email corresponding to quay registry ID


## Declare all the global variables under this
## Global variables can be accessed across all the charts including sub-charts
global:
  commonGate:
    enabled: true
  # Spinnaker Deck URL configuration; url overwhich spinnaker deck will be accessed
  spinDeck:
    host: spin.ds.training.opsmx.net

  # Spinnaker Gate URL configuration; url overwhich spinnaker gate will be accessed
  spinGate:
    host: spin-gate.ds.training.opsmx.net
  ## OES-UI url configuration
  oesUI:
    host: oes.ds.training.opsmx.net

  ## OES-Gate url configuration
  oesGate:
    host: oes-gate.ds.training.opsmx.net


sapor:
  config:
    encrypt:
      enabled: true
      key: Q7udUkHPuA3VnNlOtksSgQ # ex: Q7udUkHPuA3VnNlOtksSgQ     #encryption key needed for sapor to startup from 3.9

spinnaker:
  # Initialize gitOps style Halyard
  gitopsHalyard:
    enabled: true
    repo:
      type: git # git, s3, stash(bitbucket server) use a different sample values file for s3/bitbuck-stash
      ## Configure below fields only if repo type is git/stash. Skip to s3 section if type is s3
      baseUrlHostName: github.com    # Specify it if git url is something other than github.com
      organization: kishore438 # project name 
      # Specify project name only if repo is under a project
      projectName: ""
      repository: stanops39 # repo name for GitOps Halyard (Sample Reference: https://github.com/OpsMx/sample-gitops-repo.git).
      dynamicAccRepository: stanops39 # Please provide the repo name of the GitOps Dynamic Accounts Directory.Can be same as Hal repo. 
      halConfigPath: / #hal config path configuration path supports relative path from the root folder must be same as  dynAccntConfigPath
      dynAccntConfigPath: / #dymanic account configuration path supports relative path from the root folder must be same as halConfigPath
      username: kishore438  # Username to authenticate with git/stash repo
      token: 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  # Token corresponding to above username
    secretName: opsmx-gitops-auth
    # Promote applications and pipelines from one environment to another or take backup
    pipelinePromotion:
      enabled: true
      type: git  # git, s3, stash
      organization: kishore438   # Also called "project" in some repos
      repository: stanops39 # bucket name in case of S3
      rootFolder: pipeline/
      baseUrl: github.com  #  "git_url"
      username: kishore438 # git user
      token: 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 # ex: ghp_lqNYLgwGsUO0obycpcr2qyqDf # user token
      branch: master # branch to which changes needs to be pushed ex: testbranch
      usermail: example@example.com
      apiUrl: https://api.github.com/repos # ex: "https://api.github.com/repos"  # api url to create PRs
      createPR: false
      autoApprovePR: false
      targetBranch: master # the branch to which pr to be raised
      approvingUser:   ### user who is going to approve the pr
      approverToken:  ## approver user token

      #for deleting pipeline in spinnaker
      deleteOnSyncSpin: false
      #not implemented
      deleteOnSyncRepo: false

  ## Auth mechanism and credentials to be used by spin-cli for creating the sample pipelines
  ## Here basic ldap auth is used by default; everything under spinCli will be pasted in ~/.spin/config
  spinCli:
    gate:
      endpoint: http://oes-gate:8084 # Should same as the spin-gate URL
    auth:
      enabled: true
      basic:
        username: admin          # Please update as required
        password: opsmxadmin123  # Please update as required
