{{- if and (.Values.db.enabled) (or (eq .Values.installationMode "OES-AP")  (eq .Values.installationMode "EASY")) -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
{{ include "isd.standard-annotations" . | indent 4 }}
  labels:
    app: oes
    component: db
{{ include "oes.standard-labels" . | indent 4 }}
  name: oes-db
spec:
  podManagementPolicy: {{ .Values.db.podManagementPolicy }}
  replicas: 1
  serviceName: oes-db
  selector:
    matchLabels:
      app: oes
      component: db
  template:
    metadata:
      annotations:
{{- if .Values.db.annotations -}}
{{ toYaml .Values.db.annotations | nindent 8 }}
{{- end }}
      labels:
        app: oes
        component: db
{{ include "oes.standard-labels" . | indent 8 }}
    spec:
      {{- if .Values.imagePullSecret}}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret}}
      {{- end }}
      containers:
      - image: {{ template "db.image" . }}
        imagePullPolicy: {{ .Values.db.image.pullPolicy }}
        name: oes-db
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - /opt/opsmx/bin/stop.sh
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - mountPath: "/var/lib/pgsql-pv"
          name: oes-db-postgresql
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 10
          periodSeconds: 5
      {{- if and (not .Values.global.openshift) (.Values.db.securityContext) }}
      securityContext:
{{ toYaml .Values.db.securityContext | indent 8 }}
      {{- else }}
      {{- if and (.Values.global.openshift) (.Values.global.securityContext) }}
      securityContext:
{{ toYaml .Values.global.securityContext | indent 8 }}
      {{- else }}
      {{- if and (.Values.global.openshift) (not .Values.global.securityContext) }}
      securityContext: {{ default "{}" }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- if .Values.global.affinity }}
      affinity:
{{ toYaml .Values.global.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.global.tolerations }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      labels:
        app: oes
        component: db
      name: oes-db-postgresql
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.db.storageMountSize }}
      volumeMode: Filesystem
      {{- if .Values.db.storageClassName }}
      storageClassName: {{ .Values.db.storageClassName }}
      {{- end -}}
{{- end -}}
