{{- if not (.Values.global.createIngress) }}
{{- if not (.Values.gitopsHalyard.mTLS.enabled) }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spin
    stack: deck
{{ include "oes.standard-labels" . | indent 4 }}
{{- if .Values.global.spinDeck.serviceAnnotations }}
  annotations:
{{ toYaml .Values.global.spinDeck.serviceAnnotations | indent 4 }}
{{- end }}
  name: spin-deck-lb
spec:
  type: {{ .Values.k8sServiceType }}
  ports:
   - name: "https"
     port: 443
     targetPort: 9000
   - name: "http"
     port: 80
     protocol: TCP
     {{- if eq .Values.k8sServiceType "NodePort" }}
     nodePort: {{ .Values.global.spinDeck.port }}
     {{- end }}
     targetPort: 9000
  selector:
    cluster: spin-deck
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spin
    stack: gate
{{ include "oes.standard-labels" . | indent 4 }}
{{- if .Values.global.spinGate.serviceAnnotations }}
  annotations:
{{ toYaml .Values.global.spinGate.serviceAnnotations | indent 4 }}
{{- end }}
  name: spin-gate-lb
spec:
  type: {{ .Values.k8sServiceType }}
  ports:
   - name: https
     port: 443
     targetPort: 8084
   - name: "http"
     port: 80
     protocol: TCP
     {{- if eq .Values.k8sServiceType "NodePort" }}
     nodePort: {{ .Values.global.spinGate.port }}
     {{- end }}
     targetPort: 8084
  selector:
    cluster: spin-gate
{{- end }}
---
{{- if (.Values.gitopsHalyard.gatex509.enabled) }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spin
    cluster: spin-gate
{{- if .Values.global.spinGate.serviceAnnotations }}
  annotations:
{{ toYaml .Values.global.spinGate.serviceAnnotations | indent 4 }}
{{- end }}
  name: spin-x509gate
spec:
  ports:
  - port: 8085
    protocol: TCP
    targetPort: 8085
  - port: 443
    protocol: TCP
    targetPort: 8085
  selector:
    app: spin
    cluster: spin-gate
  sessionAffinity: None
  type: LoadBalancer
{{- end }}
{{- end }}
