job:
  preconfigured:
    kubernetes:
      - label: Policy Stage
        type: Policy Stage
        description: Spinnaker Policy Evaluation and Decision Stage
        cloudProvider: kubernetes
        account: default
        waitForCompletion: true
        application: spin
        parameters:
          - defaultValue: "http://oes-sapor:8085"
            description: Please enter the POLICY Proxy Hostname and Port
            label: Policy Proxy
            mapping: 'manifest.spec.template.spec.containers[0].env[0].value'
            name: policyurl
          - defaultValue: "/v1/data/opa/pipelines/datetimeslot"
            description: Please enter Policy path that applies to this stage 
            label: Policy Path
            mapping: 'manifest.spec.template.spec.containers[0].env[1].value'
            name: policypath
          - defaultValue: ""
            description: Please enter the Payload in single line 
            label: Payload
            mapping: 'manifest.spec.template.spec.containers[0].env[2].value'
            name: payload
        manifest:
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: policystage
            namespace: default
          spec:
            backoffLimit: 0
            template:
              spec:
                containers:
                  - args:
                      -
                    env:
                      - name: policyurl
                        value:
                      - name: policypath
                        value:
                      - name: payload
                        value:
                      - name: application
                        value: "${execution.application}"
                      - name: name
                        value: "${execution.name}"
                      - name: time
                        value: "${{execution.startTime} .toString()}"
                      - name: user
                        value: "${execution.authentication.user}"
                    image: 'opsmxdev/policy:v1'
                    imagePullPolicy: Always
                    name: policystage
                restartPolicy: Never
      - label: VerificationGate
        cloudProvider: kubernetes
        application: spin
        description: Stage for Verification Gate
        propertyFile: verificationgate
        account: default
        type: Verification
        waitForCompletion: true
        parameters:
          - defaultValue: ""
            description: Please enter the Gate URL
            label: Gate Url
            mapping: 'manifest.spec.template.spec.containers[0].env[0].value'
            name: gateurl
          - defaultValue: "0.1" 
            description: Please enter the Life Time in Hours like 0.5
            label: LifeTimeHours
            mapping: 'manifest.spec.template.spec.containers[0].env[1].value'
            name: lifetime
          - defaultValue: "70" 
            description: Please enter the Minimum Canary Result
            label: Minimum CanaryResult
            mapping: 'manifest.spec.template.spec.containers[0].env[2].value'
            name: minicanaryresult
          - defaultValue: "90" 
            description: Please enter the Canry Result Score
            label: CanaryResult Score
            mapping: 'manifest.spec.template.spec.containers[0].env[3].value'
            name: canaryresultscore
          - defaultValue: "true" 
            description: Please Enable Log Analysis with true / false
            label: Log Analysis
            mapping: 'manifest.spec.template.spec.containers[0].env[4].value'
            name: log
          - defaultValue: "true"
            description: Please Enable Metric Analysis with true / false
            label: Metric Analysis
            mapping: 'manifest.spec.template.spec.containers[0].env[5].value'
            name: metric
          - defaultValue: ""
            description: Please enter Baseline Start Time in Epoch format. If it is empty will take it as current time
            label: Baseline StartTime 
            mapping: 'manifest.spec.template.spec.containers[0].env[6].value'
            name: baselinestarttime
          - defaultValue: "" 
            description: Please enter Canry Start Time  in Epoch format. If it is empty will take it as current time
            label: Canary StartTime
            mapping: 'manifest.spec.template.spec.containers[0].env[7].value'
            name: canarystarttime
          - defaultValue: "" 
            description: Please enter Gate Name that is created in OES
            label: Gate Name
            mapping: 'manifest.spec.template.spec.containers[0].env[8].value'
            name: gate
        manifest:
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: verificationgate
            namespace: default
          spec:
            backoffLimit: 0
            template:
              spec:
                containers:
                  - args:
                      -
                    env:
                      - name: gateurl
                        value:
                      - name: lifetime
                        value:
                      - name: minicanaryresult
                        value:
                      - name: canaryresultscore
                        value:
                      - name: log
                        value:
                      - name: metric
                        value:
                      - name: baselinestarttime
                        value:
                      - name: canarystarttime
                        value:
                      - name: gate
                        value:
                      - name: application
                        value: "${execution.application}"
                      - name: service
                        value: "${execution.name}"
                      - name: time
                        value: "${{execution.startTime} .toString()}"
                    image: 'opsmxdev/verificationgate-stage:v1'
                    imagePullPolicy: Always
                    name: verificationgate
                restartPolicy: Never
      - label: VisibilityApproval
        cloudProvider: kubernetes
        credentials: default
        application: spin
        description: Stage for Visibility Approval
        propertyFile: visibilityapprove
        account: default
        type: Visibility Approval
        waitForCompletion: true
        parameters:
          - defaultValue: "" 
            description: Please enter the Gate URL
            label: Gate Url
            mapping: 'manifest.spec.template.spec.containers[0].env[0].value'
            name: gateurl
          - defaultValue: ""
            description: Please enter the JIRA ID
            label: Jira Id 
            mapping: 'manifest.spec.template.spec.containers[0].env[1].value'
            name: jiraid
          - defaultValue: ""
            description: Please enter the Git Repo Name
            label: Git Repo
            mapping: 'manifest.spec.template.spec.containers[0].env[2].value'
            name: gitrepo
          - defaultValue: ""
            description: Please enter the Git Commit Id 
            label: Git Commit Id 
            mapping: 'manifest.spec.template.spec.containers[0].env[3].value'
            name: gitcommitid
          - defaultValue: ""
            description: Please enter the Jenins Job
            label: Jenkins Job Name
            mapping: 'manifest.spec.template.spec.containers[0].env[4].value'
            name: jenkinsjob
          - defaultValue: ""
            description: Please enter the Jenkins Build No 
            label: Jenkins Build No 
            mapping: 'manifest.spec.template.spec.containers[0].env[5].value'
            name: jenkinsbuild
          - defaultValue: ""
            description: Please enter the Autopilot Canary
            label: Autopilot Canary Id
            mapping: 'manifest.spec.template.spec.containers[0].env[6].value'
            name: canaryid
          - defaultValue: ""
            description: Please enter the Sonarqube Prject Key
            label: Sonarqube Project Key
            mapping: 'manifest.spec.template.spec.containers[0].env[7].value'
            name: projectkey
        manifest:
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: visibilityapprove
            namespace: default 
          spec:
            backoffLimit: 0
            template:
              spec:
                containers:
                  - args:
                      -
                    env:
                      - name: gateurl
                        value:
                      - name: jiraid
                        value:
                      - name: gitrepo
                        value:
                      - name: gitcommitid
                        value:
                      - name: jenkinsjob
                        value:
                      - name: jenkinsbuild
                        value:
                      - name: canaryid
                        value:
                      - name: projectkey
                        value: 
                    image: 'opsmxdev/visibility-stage:v1'
                    imagePullPolicy: Always
                    name: visibilityapprove
                restartPolicy: Never
      - label: TestVerification
        cloudProvider: kubernetes
        application: spin
        description: Stage for TestVerification
        propertyFile: testverification
        account: default
        type: Test Verification
        waitForCompletion: true
        parameters:
          - defaultValue: ""
            description: Please enter the Gate URL
            label: Gate Url
            mapping: 'manifest.spec.template.spec.containers[0].env[0].value'
            name: gateurl
          - defaultValue: "0.1" 
            description: Please enter the Life Time in Hours like 0.5
            label: LifeTimeHours
            mapping: 'manifest.spec.template.spec.containers[0].env[1].value'
            name: lifetime
          - defaultValue: "70" 
            description: Please enter the Minimum Canary Result
            label: Minimum CanaryResult
            mapping: 'manifest.spec.template.spec.containers[0].env[2].value'
            name: minicanaryresult
          - defaultValue: "90" 
            description: Please enter the Canry Result Score
            label: CanaryResult Score
            mapping: 'manifest.spec.template.spec.containers[0].env[3].value'
            name: canaryresultscore
          - defaultValue: "true" 
            description: Please Enable Log Analysis with true / false
            label: Log Analysis
            mapping: 'manifest.spec.template.spec.containers[0].env[4].value'
            name: log
          - defaultValue: ""
            description: Please enter Baseline Start Time in Epoch format. If it is empty will take it as current time
            label: Baseline StartTime 
            mapping: 'manifest.spec.template.spec.containers[0].env[5].value'
            name: baselinestarttime
          - defaultValue: "" 
            description: Please enter New Start Time  in Epoch format. If it is empty will take it as current time
            label: New StartTime
            mapping: 'manifest.spec.template.spec.containers[0].env[6].value'
            name: canarystarttime
          - defaultValue: "" 
            description: Please enter Gate Name that is created in OES
            label: Gate Name
            mapping: 'manifest.spec.template.spec.containers[0].env[7].value'
            name: gate
          - defaultValue: ""
            description: Please enter the Field name which contains Test Run Id in the Index eg., TestRunId
            label: Test Run Key
            mapping: 'manifest.spec.template.spec.containers[0].env[8].value'
            name: testrunkey
          - defaultValue: ""
            description: Please enter Baseline Test Run Id of the Test Run to be used as baseline eg., 100
            label: Baseline Test Run Id
            mapping: 'manifest.spec.template.spec.containers[0].env[9].value'
            name: baselinetestrunid
          - defaultValue: ""
            description: Please enter New Test Run Id Id of the current Test Run eg., 227
            label: New Test Run Id
            mapping: 'manifest.spec.template.spec.containers[0].env[10].value'
            name: newtestrunid
          - defaultValue: ""
            description: Please enter Metadata associated with the current Test Run eg., { "Build Info" "http://opsmx.jenkins.com/123", "Code Repository" "http://opsmx.github.com", "Version" "v1.09" }
            label: Test Run Info
            mapping: 'manifest.spec.template.spec.containers[0].env[11].value'
            name: testruninfo
        manifest:
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: testverification
            namespace: default
          spec:
            backoffLimit: 0
            template:
              spec:
                containers:
                  - args:
                      -
                    env:
                      - name: gateurl
                        value:
                      - name: lifetime
                        value:
                      - name: minicanaryresult
                        value:
                      - name: canaryresultscore
                        value:
                      - name: log
                        value:
                      - name: baselinestarttime
                        value:
                      - name: canarystarttime
                        value:
                      - name: gate
                        value:
                      - name: testrunkey
                        value:
                      - name: baselinetestrunid
                        value:
                      - name: newtestrunid
                        value:
                      - name: testruninfo
                        value:
                      - name: application
                        value: "${execution.application}"
                      - name: service
                        value: "${execution.name}"
                      - name: time
                        value: "${{execution.startTime} .toString()}"
                    image: 'opsmxdev/testverification:v1'
                    imagePullPolicy: Always
                    name: testverification
                restartPolicy: Never
