job:
  preconfigured:
    kubernetes:
      - label: pipelineSyncToGit
        cloudProvider: kubernetes
        credentials: default
        description: Update git with pipelines in Spinnaker
        account: default
        application: gitopsHalyard.pipelinePromotion
        type: pipelineSyncToGit
        waitForCompletion: true
        parameters:
          - defaultValue: "app1,app2,..."
            description: "Please enter spinnaker applications separated by comma"
            label: spinnaker applications
            mapping: 'manifest.spec.template.spec.containers[0].env[0].value'
            name: spinnaker_applications
          - defaultValue: "pipeline1,pipeline2..."
            description: "Please enter spinnaker pipelines separated by comma"
            label: pipieline names
            mapping: 'manifest.spec.template.spec.containers[0].env[1].value'
            name: spinnaker_pipelines
        manifest:
            apiVersion: batch/v1
            kind: Job
            metadata:
              generateName: pipepromot-
              namespace: default
            spec:
              backoffLimit: 0
              template:
                spec:
                  containers:
                  - command: ["bash", "scripts/deployer.sh"]
                    image: 'opsmxdev/pipepromot:1.0'
                    imagePullPolicy: Always
                    name: pipepromot
                    volumeMounts:
                    - mountPath: /home/opsmx/scripts
                      name: pipe-promot-scripts
                    - mountPath: /home/opsmx/.spin
                      name: spin-cli-config
                    env:
                      - name: spinnaker_applications
                        value: 'will be replaced'
                      - name: spinnaker_pipelines
                        value: 'will be replaced'
                      - name: command
                        value: 'upload'
                      - name: git_friendly_username
                        valueFrom:
                          configMapKeyRef:
                            name: pipe-promot-config
                            key: git_friendly_username
                      - name: git_friendly_username
                        valueFrom:
                          configMapKeyRef:
                            name: pipe-promot-config
                            key: git_friendly_username
                      - name: git_project
                        valueFrom:
                          configMapKeyRef:
                            name: pipe-promot-config
                            key: git_project
                      - name: git_refresh_enabled
                        valueFrom:
                          configMapKeyRef:
                            name: pipe-promot-config
                            key: git_refresh_enabled
                      - name: git_repo
                        valueFrom:
                          configMapKeyRef:
                            name: pipe-promot-config
                            key: git_repo
                      - name: git_user_email
                        valueFrom:
                          configMapKeyRef:
                            name: pipe-promot-config
                            key: git_user_email
                      - name: ignore_spin_errors
                        valueFrom:
                          configMapKeyRef:
                            name: pipe-promot-config
                            key: ignore_spin_errors
                      - name: git_secret_token
                        valueFrom:
                          secretKeyRef:
                            name: git-token
                            key: git_secret_token
                      - name: debug
                        valueFrom:
                          configMapKeyRef:
                            name: pipe-promot-config
                            key: debug
                      - name: pipelineconfig
                        valueFrom:
                          configMapKeyRef:
                            name: pipe-promot-config
                            key: pipelineconfig
                      - name: pipelineconfigdir
                        valueFrom:
                          configMapKeyRef:
                            name: pipe-promot-config
                            key: pipelineconfigdir
                      - name: pipelinecreateconf
                        valueFrom:
                          configMapKeyRef:
                            name: pipe-promot-config
                            key: pipelinecreateconf
                  volumes:
                  - configMap:
                      defaultMode: 420
                      name: pipe-promot-scripts
                    name: pipe-promot-scripts
                  - name: spin-cli-config
                    secret:
                      defaultMode: 420
                      secretName: spin-cli-config
                  restartPolicy: Never
                  serviceAccountName: default
      - label: pipelineSyncToSpinnaker
        cloudProvider: kubernetes
        credentials: default
        description: Sync Spinnaker pipelines from git
        account: default
        application: gitopsHalyard.pipelinePromotion
        type: pipelineSyncToSpinnaker
        waitForCompletion: true
        parameters:
          - defaultValue: "app1,app2,..."
            description: "Please enter spinnaker applications separated by comma"
            label: spinnaker applications
            mapping: 'manifest.spec.template.spec.containers[0].env[0].value'
            name: spinnaker_applications
          - defaultValue: "pipeline1,pipeline2..."
            description: "Please enter spinnaker pipelines separated by comma"
            label: pipieline names
            mapping: 'manifest.spec.template.spec.containers[0].env[1].value'
            name: spinnaker_pipelines
        manifest:
            apiVersion: batch/v1
            kind: Job
            metadata:
              generateName: pipepromot-
              namespace: default
            spec:
              backoffLimit: 0
              template:
                spec:
                  containers:
                  - command: ["bash", "scripts/deployer.sh"]
                    image: 'opsmxdev/pipepromot:1.0'
                    imagePullPolicy: Always
                    name: pipepromot
                    volumeMounts:
                    - mountPath: /home/opsmx/scripts
                      name: pipe-promot-scripts
                    - mountPath: /home/opsmx/.spin
                      name: spin-cli-config
                    env:
                      - name: spinnaker_applications
                        value: 'will be replaced'
                      - name: spinnaker_pipelines
                        value: 'will be replaced'
                      - name: command
                        value: 'download'
                      - name: git_friendly_username
                        valueFrom:
                          configMapKeyRef:
                            name: pipe-promot-config
                            key: git_friendly_username
                      - name: git_friendly_username
                        valueFrom:
                          configMapKeyRef:
                            name: pipe-promot-config
                            key: git_friendly_username
                      - name: git_project
                        valueFrom:
                          configMapKeyRef:
                            name: pipe-promot-config
                            key: git_project
                      - name: git_refresh_enabled
                        valueFrom:
                          configMapKeyRef:
                            name: pipe-promot-config
                            key: git_refresh_enabled
                      - name: git_repo
                        valueFrom:
                          configMapKeyRef:
                            name: pipe-promot-config
                            key: git_repo
                      - name: git_user_email
                        valueFrom:
                          configMapKeyRef:
                            name: pipe-promot-config
                            key: git_user_email
                      - name: ignore_spin_errors
                        valueFrom:
                          configMapKeyRef:
                            name: pipe-promot-config
                            key: ignore_spin_errors
                      - name: git_secret_token
                        valueFrom:
                          secretKeyRef:
                            name: git-token
                            key: git_secret_token
                      - name: debug
                        valueFrom:
                          configMapKeyRef:
                            name: pipe-promot-config
                            key: debug
                      - name: pipelineconfig
                        valueFrom:
                          configMapKeyRef:
                            name: pipe-promot-config
                            key: pipelineconfig
                      - name: pipelineconfigdir
                        valueFrom:
                          configMapKeyRef:
                            name: pipe-promot-config
                            key: pipelineconfigdir
                      - name: pipelinecreateconf
                        valueFrom:
                          configMapKeyRef:
                            name: pipe-promot-config
                            key: pipelinecreateconf
                  volumes:
                  - configMap:
                      defaultMode: 420
                      name: pipe-promot-scripts
                    name: pipe-promot-scripts
                  - name: spin-cli-config
                    secret:
                      defaultMode: 420
                      secretName: local-spin-cli-config
                  restartPolicy: Never
                  serviceAccountName: default
      - label: Policy Stage
        type: Policy Stage
        description: Spinnaker Policy Evaluation and Decision Stage
        cloudProvider: kubernetes
        account: default
        waitForCompletion: true
        application: spin
        parameters:
          - defaultValue: "http://oes-sapor:8085"
            description: Please enter the POLICY Proxy Hostname and Port
            label: Policy Proxy
            mapping: 'manifest.spec.template.spec.containers[0].env[0].value'
            name: policyurl
          - defaultValue: "/v1/data/opa/pipelines/datetimeslot"
            description: Please enter Policy path that applies to this stage 
            label: Policy Path
            mapping: 'manifest.spec.template.spec.containers[0].env[1].value'
            name: policypath
          - defaultValue: ""
            description: Please enter the Payload in single line 
            label: Payload
            mapping: 'manifest.spec.template.spec.containers[0].env[2].value'
            name: payload
        manifest:
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: policystage
            namespace: default
          spec:
            backoffLimit: 0
            template:
              spec:
                containers:
                  - args:
                      -
                    env:
                      - name: policyurl
                        value:
                      - name: policypath
                        value:
                      - name: payload
                        value:
                      - name: application
                        value: "${execution.application}"
                      - name: name
                        value: "${execution.name}"
                      - name: time
                        value: "${{execution.startTime} .toString()}"
                      - name: user
                        value: "${execution.authentication.user}"
                    image: 'opsmxdev/policy:v1'
                    imagePullPolicy: Always
                    name: policystage
                restartPolicy: Never
      - label: VerificationGate
        cloudProvider: kubernetes
        application: spin
        description: Stage for Verification Gate
        propertyFile: verificationgate
        account: default
        type: Verification
        waitForCompletion: true
        parameters:
          - defaultValue: ""
            description: Please enter the Gate URL
            label: Gate Url
            mapping: 'manifest.spec.template.spec.containers[0].env[0].value'
            name: gateurl
          - defaultValue: "0.1" 
            description: Please enter the Life Time in Hours like 0.5
            label: LifeTimeHours
            mapping: 'manifest.spec.template.spec.containers[0].env[1].value'
            name: lifetime
          - defaultValue: "70" 
            description: Please enter the Minimum Canary Result
            label: Minimum CanaryResult
            mapping: 'manifest.spec.template.spec.containers[0].env[2].value'
            name: minicanaryresult
          - defaultValue: "90" 
            description: Please enter the Canry Result Score
            label: CanaryResult Score
            mapping: 'manifest.spec.template.spec.containers[0].env[3].value'
            name: canaryresultscore
          - defaultValue: "true" 
            description: Please Enable Log Analysis with true / false
            label: Log Analysis
            mapping: 'manifest.spec.template.spec.containers[0].env[4].value'
            name: log
          - defaultValue: "true"
            description: Please Enable Metric Analysis with true / false
            label: Metric Analysis
            mapping: 'manifest.spec.template.spec.containers[0].env[5].value'
            name: metric
          - defaultValue: ""
            description: Please enter Baseline Start Time in Epoch format. If it is empty will take it as current time
            label: Baseline StartTime 
            mapping: 'manifest.spec.template.spec.containers[0].env[6].value'
            name: baselinestarttime
          - defaultValue: "" 
            description: Please enter Canry Start Time  in Epoch format. If it is empty will take it as current time
            label: Canary StartTime
            mapping: 'manifest.spec.template.spec.containers[0].env[7].value'
            name: canarystarttime
          - defaultValue: "" 
            description: Please enter Gate Name that is created in OES
            label: Gate Name
            mapping: 'manifest.spec.template.spec.containers[0].env[8].value'
            name: gate
        manifest:
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: verificationgate
            namespace: default
          spec:
            backoffLimit: 0
            template:
              spec:
                containers:
                  - args:
                      -
                    env:
                      - name: gateurl
                        value:
                      - name: lifetime
                        value:
                      - name: minicanaryresult
                        value:
                      - name: canaryresultscore
                        value:
                      - name: log
                        value:
                      - name: metric
                        value:
                      - name: baselinestarttime
                        value:
                      - name: canarystarttime
                        value:
                      - name: gate
                        value:
                      - name: application
                        value: "${execution.application}"
                      - name: service
                        value: "${execution.name}"
                      - name: time
                        value: "${{execution.startTime} .toString()}"
                    image: 'opsmxdev/verificationgate-stage:v1'
                    imagePullPolicy: Always
                    name: verificationgate
                restartPolicy: Never
      - label: VisibilityApproval
        cloudProvider: kubernetes
        credentials: default
        application: spin
        description: Stage for Visibility Approval
        propertyFile: visibilityapprove
        account: default
        type: Visibility Approval
        waitForCompletion: true
        parameters:
          - defaultValue: "" 
            description: Please enter the Gate URL
            label: Gate Url
            mapping: 'manifest.spec.template.spec.containers[0].env[0].value'
            name: gateurl
          - defaultValue: ""
            description: Please enter the JIRA ID
            label: Jira Id 
            mapping: 'manifest.spec.template.spec.containers[0].env[1].value'
            name: jiraid
          - defaultValue: ""
            description: Please enter the Git Repo Name
            label: Git Repo
            mapping: 'manifest.spec.template.spec.containers[0].env[2].value'
            name: gitrepo
          - defaultValue: ""
            description: Please enter the Git Commit Id 
            label: Git Commit Id 
            mapping: 'manifest.spec.template.spec.containers[0].env[3].value'
            name: gitcommitid
          - defaultValue: ""
            description: Please enter the Jenins Job
            label: Jenkins Job Name
            mapping: 'manifest.spec.template.spec.containers[0].env[4].value'
            name: jenkinsjob
          - defaultValue: ""
            description: Please enter the Jenkins Build No 
            label: Jenkins Build No 
            mapping: 'manifest.spec.template.spec.containers[0].env[5].value'
            name: jenkinsbuild
          - defaultValue: ""
            description: Please enter the Autopilot Canary
            label: Autopilot Canary Id
            mapping: 'manifest.spec.template.spec.containers[0].env[6].value'
            name: canaryid
          - defaultValue: ""
            description: Please enter the Sonarqube Prject Key
            label: Sonarqube Project Key
            mapping: 'manifest.spec.template.spec.containers[0].env[7].value'
            name: projectkey
        manifest:
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: visibilityapprove
            namespace: default 
          spec:
            backoffLimit: 0
            template:
              spec:
                containers:
                  - args:
                      -
                    env:
                      - name: gateurl
                        value:
                      - name: jiraid
                        value:
                      - name: gitrepo
                        value:
                      - name: gitcommitid
                        value:
                      - name: jenkinsjob
                        value:
                      - name: jenkinsbuild
                        value:
                      - name: canaryid
                        value:
                      - name: projectkey
                        value: 
                    image: 'opsmxdev/visibility-stage:v1'
                    imagePullPolicy: Always
                    name: visibilityapprove
                restartPolicy: Never
