apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    moniker.spinnaker.io/application: spin
  name: {{ template "spinnaker.fullname" . }}-halyard
  labels:
{{ include "spinnaker.standard-labels" . | indent 4 }}
spec:
  serviceName: {{ template "spinnaker.fullname" . }}-halyard
  replicas: 1
  selector:
    matchLabels:
{{ include "spinnaker.standard-selector-labels" . | indent 6 }}
      component: halyard
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap/halyard-init-script.yaml") . | sha256sum }}
      {{- if .Values.halyard.annotations }}
{{ toYaml .Values.halyard.annotations | indent 8 }}
      {{- end }}
      labels:
{{ include "spinnaker.standard-labels" . | indent 8 }}
        component: halyard
    spec:
      {{- if .Values.serviceAccount.halyardName }}
      serviceAccountName: {{ .Values.serviceAccount.halyardName }}
      {{- else }}
      serviceAccountName: {{ template "spinnaker.fullname" . }}-halyard
      {{- end }}
      {{- if and (.Values.global.openshift) (not .Values.global.securityContext) }}
      securityContext: {{ default "{}" }}
      {{- else }}
      {{- if and (.Values.global.openshift) (.Values.global.securityContext) }}
      securityContext:
{{ toYaml .Values.global.securityContext | indent 8 }}
      {{- else }}
      {{- if and (not .Values.global.openshift) (.Values.securityContext) }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
      {{- end }}
      {{- end }}
      {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
    {{- end }}
      initContainers:
      {{- if .Values.gitopsHalyard.repo.sshkeysecret }}
      - image: k8s.gcr.io/git-sync:v3.1.6
        name: git-sync
        args:
          - "-repo=git@{{ .Values.gitopsHalyard.repo.baseUrlHostName }}:{{ .Values.gitopsHalyard.repo.organization }}/{{ .Values.gitopsHalyard.repo.repository }}"
          - "-branch={{ .Values.gitopsHalyard.repo.halConfigBranch }}"
          - "-depth=1"
          - "-max-sync-failures=-1"
          - "-root=/tmp/spinnaker/"
          - "-dest=test"
          - "-wait=60"
          - "-ssh=true"
          - "-one-time=true"
        volumeMounts:
        - name: ssh-secret
          mountPath: /etc/git-secret
          readOnly: true
        - mountPath: /tmp/config
          name: halyard-config
        - mountPath: /tmp/service-settings
          name: service-settings
        - mountPath: /tmp/spinnaker
          name: halyard-home
        - mountPath: /tmp/additionalProfileConfigMaps
          name: additional-profile-config-maps
        - mountPath: /tmp/initscript
          name: halyard-initscript
        securityContext:
          runAsUser: 65533 # git-sync-user
      {{- end }}
      - name: "create-halyard-local"
      {{- if .Values.gitopsHalyard.enabled }}
        image: {{ .Values.global.customImages.registry }}/awsgit:v3-js
      {{- else }}
        image: {{ .Values.halyard.image.repository }}:{{ .Values.halyard.image.tag }}
      {{- end }}
        command:
        {{- if .Values.gitopsHalyard.enabled }}
        - sh
        {{- else }}
        - bash
        {{- end }}
        - /tmp/initscript/init.sh
        {{- if and (.Values.gitopsHalyard.enabled) (.Values.global.gitea.enabled) }}
        env:
        - name: SPINNAKER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GITEA_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.gitea.admin.existingSecret }}
              key: username
        - name: GITEA_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.gitea.admin.existingSecret }}
              key: password
        {{- end }}
        {{- if .Values.gitopsHalyard.enabled }}
        {{- if or (eq .Values.gitopsHalyard.repo.type "git") (eq .Values.gitopsHalyard.repo.type "stash") }}
        {{- if not (.Values.global.gitea.enabled) }}
        env:
        - name: GIT_CLONE_PARAM
          valueFrom:
            secretKeyRef:
              name: {{ .Values.gitopsHalyard.secretName }}
              key: gitcloneparam
        - name: GIT_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.gitopsHalyard.secretName }}
              key: gituser
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.gitopsHalyard.secretName }}
              key: gittoken
        - name: DYNAMIC_ACCOUNTS_REPO
          valueFrom:
            secretKeyRef:
              name: {{ .Values.gitopsHalyard.secretName }}
              key: dynamicaccountsgituri
        - name: SPINNAKER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- end }}
        {{- end }}
        {{- end }}
        {{- if and (.Values.gitopsHalyard.enabled) (eq .Values.gitopsHalyard.repo.type "s3") }}
        env:
        - name: SPINNAKER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: S3_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.gitopsHalyard.secretName }}
              key: s3accesskey
        - name: S3_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.gitopsHalyard.secretName }}
              key: s3secretkey
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.gitopsHalyard.secretName }}
              key: s3bucket
        - name: S3_REGION
          valueFrom:
            secretKeyRef:
              name: {{ .Values.gitopsHalyard.secretName }}
              key: s3region
        {{- end }}
        volumeMounts:
        {{- if .Values.gitopsHalyard.repo.sshkeysecret }}
        - mountPath: /etc/git-secret
          name: ssh-secret
          readOnly: true
        {{- end }}
        - name: halyard-config
          mountPath: /tmp/config
        - name: service-settings
          mountPath: /tmp/service-settings
        {{- if .Values.halyard.serviceConfigs }}
        - name: service-configs
          mountPath: /tmp/service-configs
        {{- end }}
        - name: halyard-home
          mountPath: /tmp/spinnaker
        - name: additional-profile-config-maps
          mountPath: /tmp/additionalProfileConfigMaps
        {{- if .Values.halyard.bom }}
        - name: halyard-bom
          mountPath: /tmp/halyard-bom
        {{- end }}
        - name: halyard-initscript
          mountPath: /tmp/initscript
        {{- if .Values.global.customCerts.enabled }}
        - mountPath: /etc/pki/ca-trust/extracted/java/cacerts
          subPath: cacerts
          name: cacerts
        {{- end }}
      {{- if and (.Values.gitopsHalyard.enabled) (eq .Values.gitopsHalyard.repo.type "git") }}
      - name: "halyardconfig-update"
        command:
        - sh
        - /tmp/akv2k8s/run.sh
        image: {{ .Values.global.customImages.registry }}/k8s-decoder:hal
        imagePullPolicy: IfNotPresent
        resources: {}
        volumeMounts:
        - name: halyard-home
          mountPath: /tmp/spinnaker
        - name: secret-decoder
          mountPath: /tmp/akv2k8s
        {{- end }}
      {{- if .Values.gitopsHalyard.enabled }}
      - name: "halyard-overrideurl"
        command:
        - sh
        - /tmp/autoconfig/call_overrides.sh
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        image: {{ .Values.global.customImages.registry }}/bitnami-kubectl:1.18.5
        imagePullPolicy: IfNotPresent
        resources: {}
        volumeMounts:
        - name: halyard-config
          mountPath: /tmp/config
        - name: service-settings
          mountPath: /tmp/service-settings
        {{- if .Values.halyard.serviceConfigs }}
        - name: service-configs
          mountPath: /tmp/service-configs
        {{- end }}
        - name: halyard-home
          mountPath: /tmp/spinnaker
        - name: additional-profile-config-maps
          mountPath: /tmp/additionalProfileConfigMaps
        {{- if .Values.halyard.bom }}
        - name: halyard-bom
          mountPath: /tmp/halyard-bom
        {{- end }}
        - name: halyard-initscript
          mountPath: /tmp/initscript
        {{- if .Values.global.customCerts.enabled }}
        - mountPath: /etc/pki/ca-trust/extracted/java/cacerts
          subPath: cacerts
          name: cacerts
        {{- end }}
        - mountPath: /tmp/autoconfig
          name: halyard-overrideurl
      {{- end }}
      volumes:
      {{- if or .Values.gitopsHalyard.enabled (not .Values.halyard.persistence.enabled) }}
      - name: halyard-home
        emptyDir: {}
      {{- end }}
      {{- if .Values.gitopsHalyard.enabled }}
      - name: halyard-overrideurl
        configMap:
          name: {{ template "spinnaker.fullname" . }}-halyard-overrideurl
      {{- end }}
      {{- if and (.Values.gitopsHalyard.enabled) (eq .Values.gitopsHalyard.repo.type "git") }}
      - name: secret-decoder
        configMap:
          name: {{ template "spinnaker.fullname" . }}-spin-secret-decoder
      {{- end }}
      {{- if .Values.gitopsHalyard.mTLS.enabled }}
      - name: sslcerts
        secret:
          secretName: mtlscerts-pkcs12
      {{- end }}
      {{- if and .Values.kubeConfig.enabled .Values.kubeConfig.secretName }}
      - name: kube-config
        secret:
          secretName: {{ .Values.kubeConfig.secretName }}
      {{- end }}
      {{- if .Values.gcs.enabled }}
      - name: gcs-key
        secret:
        {{- if .Values.gcs.secretName }}
          secretName: {{ .Values.gcs.secretName }}
        {{- else }}
          secretName: {{ template "spinnaker.fullname" . }}-gcs
        {{- end }}
      {{- end }}
      - name: reg-secrets
        secret:
          {{- if .Values.dockerRegistryAccountSecret }}
          secretName: {{ .Values.dockerRegistryAccountSecret }}
          {{- else }}
          secretName: {{ template "spinnaker.fullname" . }}-registry
          {{- end }}
      {{- if and .Values.s3.enabled .Values.s3.accessKey .Values.s3.secretKey }}
      - name: s3-secrets
        secret:
          secretName: {{ template "spinnaker.fullname" . }}-s3
      {{- end }}
      {{- if or .Values.halyard.additionalSecrets.create (hasKey .Values.halyard.additionalSecrets "name") }}
      - name: additional-secrets
        secret:
        {{- if .Values.halyard.additionalSecrets.create }}
          secretName: {{ template "spinnaker.fullname" . }}-additional-secrets
        {{- else if .Values.halyard.additionalSecrets.name }}
          secretName: {{ .Values.halyard.additionalSecrets.name }}
        {{- end }}
      {{- end }}
      {{- if or .Values.halyard.additionalConfigMaps.create (hasKey .Values.halyard.additionalConfigMaps "name") }}
      - name: additional-config-maps
        configMap:
        {{- if .Values.halyard.additionalConfigMaps.create }}
          name: {{ template "spinnaker.fullname" . }}-additional-config-maps
        {{- else if .Values.halyard.additionalConfigMaps.name }}
          name: {{ .Values.halyard.additionalConfigMaps.name }}
        {{- end }}
      {{- end }}
      - name: additional-profile-config-maps
        configMap:
          name: {{ template "spinnaker.fullname" . }}-additional-profile-config-maps
      {{- if .Values.halyard.bom }}
      - name: halyard-bom
        configMap:
          name: {{ template "spinnaker.fullname" . }}-halyard-bom
      {{- end }}
      - name: halyard-config
        emptyDir: {}
      - name: service-settings
        configMap:
          name: {{ template "spinnaker.fullname" . }}-service-settings
      {{- if .Values.halyard.serviceConfigs }}
      - name: service-configs
        configMap:
          name: {{ template "spinnaker.fullname" . }}-service-configs
      {{- end }}
      - name: halyard-initscript
        configMap:
          name: {{ template "spinnaker.fullname" . }}-halyard-init-script
      {{- if .Values.global.customCerts.enabled }}
      - name: cacerts
        secret:
          secretName: {{ .Values.global.customCerts.secretName }}
          items:
          - key: cacerts
            path: cacerts
      {{- end }}
      {{- if .Values.gitopsHalyard.repo.sshkeysecret }}
      - name: ssh-secret
        secret:
          secretName: {{ .Values.gitopsHalyard.repo.sshsecretName }}
          defaultMode: 0400
      {{- end }}
      {{- if .Values.halyard.image.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.halyard.image.pullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
      - name: halyard
        image: {{ .Values.halyard.image.repository }}:{{ .Values.halyard.image.tag }}
        {{- if .Values.gitopsHalyard.enabled }}
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "until curl http://localhost:8064/health; do sleep 10 ;done;hal deploy apply"]
        {{- end }}
        ports:
        - containerPort: 8064
          name: daemon
        {{- if .Values.halyard.resources }}
        resources:
{{ toYaml .Values.halyard.resources | indent 10 }}
        {{- end }}
        volumeMounts:
        {{- if .Values.gcs.enabled }}
        - name: gcs-key
          mountPath: /opt/gcs
        {{- end }}
        {{- if and .Values.s3.enabled .Values.s3.accessKey .Values.s3.secretKey }}
        - name: s3-secrets
          mountPath: /opt/s3
        {{- end }}
        {{- if and .Values.kubeConfig.enabled .Values.kubeConfig.secretName }}
        - name: kube-config
          mountPath: /opt/kube
        {{- end }}
        {{- if or .Values.halyard.additionalSecrets.create (hasKey .Values.halyard.additionalSecrets "name") }}
        - name: additional-secrets
          mountPath: /opt/halyard/additionalSecrets
        {{- end }}
        {{- if or .Values.halyard.additionalConfigMaps.create (hasKey .Values.halyard.additionalConfigMaps "name") }}
        - name: additional-config-maps
          mountPath: /opt/halyard/additionalConfigMaps
        {{- end }}
        - name: halyard-home
          mountPath: /home/spinnaker
        - name: halyard-config
          mountPath: /opt/halyard/config
        - name: reg-secrets
          mountPath: /opt/registry/passwords
        {{- if .Values.global.customCerts.enabled }}
        - mountPath: /etc/pki/ca-trust/extracted/java/cacerts
          subPath: cacerts
          name: cacerts
        {{- end }}
        {{- if .Values.gitopsHalyard.mTLS.enabled }}
        - mountPath: /home/spinnaker/.hal/default/tls.crt
          subPath: tls.crt
          name: sslcerts
        - mountPath: /home/spinnaker/.hal/default/tls.key
          subPath: tls.key
          name: sslcerts
        {{- end }}
        {{- if .Values.halyard.env }}
        env:
{{ toYaml .Values.halyard.env | indent 8 }}
        {{- end }}
{{- if and (not .Values.gitopsHalyard.enabled) .Values.halyard.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: halyard-home
      labels:
{{ include "spinnaker.standard-labels-base" . | indent 8 }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- with .Values.halyard.persistence.storageClass }}
      storageClassName: {{ . }}
      {{- end }}
      resources:
        requests:
          storage: 10Gi
{{- end }}
