{{- if or (eq .Values.installationMode "OES-AP")  (eq .Values.installationMode "EASY") -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oes
    component: gate
{{ include "oes.standard-labels" . | indent 4 }}
{{- if .Values.gate.serviceAnnotations }}
  annotations:
{{ toYaml .Values.gate.serviceAnnotations | indent 4 }}
{{- end }}
  name: oes-gate
spec:
  type: {{ .Values.k8sServiceType }}
  ports:
  - name: "https"
    port: 443
    targetPort: 8084
  - name: "oes-gate-service"
    port: 8084
    protocol: TCP
    targetPort: 8084
    {{- if eq .Values.k8sServiceType "NodePort" }}
    nodePort: {{ .Values.global.oesGate.port }}
    {{- end }}
  - name: "http"
    port: 80
    targetPort: 8084
  selector:
    app: oes
    component: gate
{{- end -}}
