{{- if or (eq .Values.installationMode "OES-AP")  (eq .Values.installationMode "EASY") -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oes
    component: ui
{{ include "oes.standard-labels" . | indent 4 }}
{{- if .Values.ui.serviceAnnotations }}
  annotations:
{{ toYaml .Values.ui.serviceAnnotations | indent 4 }}
{{- end }}
  name: oes-ui
spec:
  type: {{ .Values.k8sServiceType }}
  ports:
  - name: "https"
    port: 443
    targetPort: 8080
  - name: "http"
    port: 8080
    targetPort: 8080
    {{- if eq  .Values.k8sServiceType "NodePort" }}
    nodePort: {{ .Values.global.oesUI.port }}
    {{- end }}
    {{- if eq .Values.k8sServiceType "LoadBalancer" }}
  - name: "lbhttp"
    port: 80
    targetPort: 8080
    nodePort: {{ .Values.global.oesUI.port }}
    {{- end }}
  selector:
    app: oes
    component: ui
{{- end -}}
