{{- if (eq .Values.installationMode "OES-AP") -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding # ClusterRole if you have cluster access
metadata:
  name: {{ .Release.Namespace }}-oes-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- namespace: {{ .Release.Namespace }}
  kind: ServiceAccount
  name: default
{{- end -}}
