# Enable Build Analysis
APP:
   ENVIRONMENT: dev
   DEBUG: True
   # Only accept True or False
   BIND: 0.0.0.0:5005
   WORKERS: 1
   PROTOCOL: http://
   TIMEOUT: 3600
   CELERY_ENABLED: True
   # Only accept True or False

OBJECT_STORAGE:
      ENDPOINT: http://{{ .Release.Name }}-minio:9000
      BUCKET_NAME: autopilot
POSTGRES:
      USERNAME: '{{ .Values.db.username }}'
      PASSWORD: '{{ .Values.db.password }}'
      HOST: {{ (split ":" (split "//" .Values.db.url)._1)._0 }}
      PORT: 5432
      DB: autopilotqueue

RABBITMQ:
      USERNAME: '{{ .Values.rabbitmq.username }}'
      PASSWORD: '{{ .Values.rabbitmq.password }}'
      HOST: rabbitmq-service
      PORT: 5672
