---
# Source: oes/templates/forwarder/oes-forwarder-svc-agent.yaml
apiVersion: v1
kind: Service
metadata:
  name: opsmx-controller-controller1
  labels:
    agent.opsmx.com/name: controller1
    agent.opsmx.com/role: controller
    heritage: "Helm"
    release: "RELEASE-NAME"
    chart: "oes-3.5.0"
spec:
  selector:
    app: opsmx-controller-controller1
  type: LoadBalancer
  ports:
  - name: agent-grpc
    port: 9001
    targetPort: agent-grpc
  - name: k8s-api
    port: 9002
    targetPort: k8s-api
  - name: command
    port: 9003
    targetPort: command
