{{- if or (eq .Values.installationMode "OES-AP")  (eq .Values.installationMode "EASY") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
{{ include "isd.standard-annotations" . | indent 4 }}
  labels:
    app: oes
    component: sapor
{{ include "oes.standard-labels" . | indent 4 }}
  name: oes-sapor
spec:
  replicas: {{ .Values.sapor.replicas }}
  selector:
    matchLabels:
      app: oes
      component: sapor
  template:
    metadata:
      annotations:
        checksum/configmap: {{ (.Files.Glob "config/oes-sapor/application.yml").AsConfig | sha256sum }}
        checksum/configmap: {{ (.Files.Glob "templates/forwarder/oes-forwarder-config.yaml").AsConfig | sha256sum }}
{{- if .Values.sapor.annotations -}}
        {{ toYaml .Values.sapor.annotations | nindent 8 }}
{{- end }}
      labels:
        app: oes
        component: sapor
{{ include "oes.standard-labels" . | indent 8 }}
    spec:

      initContainers:
      - name: db-check
        image: {{ .Values.global.customImages.registry }}/pgchecker:v1
        command:
          - sh
          - -c
          - |
            RABBITMQ_DEFAULT_PASS=`echo $RABBITMQ_DEFAULT_PASS | sed 's/ *$//g'`
          {{- if .Values.db.enabled }}
            echo 'Waiting for OES-DB to become ready...'
            until printf "." && nc -z -w 2 oes-db 5432; do
               sleep 2;
            done;
            echo 'OESDB OK âœ“'
            OPSMX_POSTGRESQL_PASS=`echo $OPSMX_POSTGRESQL_PASS | sed 's/ *$//g'`
            sed -e s/OPSMX_POSTGRESQL_PASS/${OPSMX_POSTGRESQL_PASS}/g /tmp/application.yml > /tmp/config/application.yml
          {{- else }}
            cp /tmp/application.yml > /tmp/config/application.yml
          {{- end }}
            sed -i s/RABBITMQ_DEFAULT_PASS/${RABBITMQ_DEFAULT_PASS}/g /tmp/config/application.yml            
            echo success
        env:
        {{- if .Values.db.enabled }}          
        - name: OPSMX_POSTGRESQL_PASS
          valueFrom:
            secretKeyRef:
              key: pgpassword
              name: oes-db
        {{- end }}              
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              key: rabbitmqpassword
              name: rabbitmq
        volumeMounts:
        - mountPath: /tmp
          name: sapor-config-volume
        - mountPath: /tmp/config
          name: sapor-config
      containers:
      - image: {{ template "sapor.image" . }}
        name: oes-sapor
        env:
       {{- if .Values.extraEnvVars }}
       {{- include "tplvalues.render" (dict "value" .Values.extraEnvVars "context" $) | nindent 8 }}
       {{- end }}
        ports:
        - containerPort: 8085
          protocol: TCP
        volumeMounts:
        {{- if .Values.forwarder.enabled }}
        - mountPath: /opt/opsmx/controller/ca.crt
          name: ca-certs-volume
          subPath: tls.crt
        - mountPath: /opt/opsmx/controller/cert/tls.crt
          name: certs-volume
          subPath: tls.crt
        - mountPath: /opt/opsmx/controller/cert/tls.key
          name: certs-volume
          subPath: tls.key
        {{- end }}
        - mountPath: /opt/opsmx/bootstrap.yml
          name: bootstrap-config-volume
          subPath: bootstrap.yml
        - mountPath: /opsmx/conf/standard-error-code.csv
          name: standard-error-conf
          subPath: standard-error-codes.csv
        - mountPath: /opt/opsmx/application.yml
          name: sapor-config
          subPath: application.yml         
        {{- if .Values.global.customCerts.enabled }}
        - mountPath: /etc/pki/ca-trust/extracted/java/cacerts
          subPath: cacerts
          name: cacerts
        {{- end }}
        {{- if .Values.sapor.config.spinnaker.x509.enabled }}
        - name: certs-x509-volume
          mountPath: /opt/opsmx/client.p12
          subPath: client.p12
        {{- end }}
        resources:
{{ toYaml .Values.sapor.resources | indent 12 }}
        readinessProbe:
          tcpSocket:
            port: 8085
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /mgmt/health
            port: 8085
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 10
      {{- if .Values.imagePullSecret}}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret}}
      {{- end }}
      {{- if and (.Values.global.openshift) (not .Values.global.securityContext) }}
      securityContext: {{ default "{}" }}
      {{- else }}
      {{- if and (.Values.global.openshift) (.Values.global.securityContext) }}
      securityContext:
{{ toYaml .Values.global.securityContext | indent 8 }}
      {{- else }}
      {{- if and (not .Values.global.openshift) (.Values.global.securityContext) }}
      securityContext:
{{ toYaml .Values.global.securityContext | indent 8 }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- if .Values.global.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.global.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.global.affinity }}
      affinity:
{{ toYaml .Values.global.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.global.tolerations }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.forwarder.enabled }}
      - secret:
          secretName: oes-control-secret
        name: certs-volume
      - secret:
          secretName: ca-secret
        name: ca-certs-volume
      {{- end }}
      {{- if .Values.global.customCerts.enabled }}
      - name: cacerts
        secret:
          secretName: {{ .Values.global.customCerts.secretName }}
          items:
          - key: cacerts
            path: cacerts
      {{- end }}
      - secret:
          items:
          - key: bootstrap.yml
            path: bootstrap.yml
          secretName: sapor-bootstrap
        name: bootstrap-config-volume
      - emptyDir: {}       
        name: sapor-config
      - configMap:
          name: oes-sapor-config
        name: sapor-config-volume  
      - configMap:
          defaultMode: 420
          items:
          - key: standard-error-codes.csv
            path: standard-error-codes.csv
          name: standard-error-codes-config
        name: standard-error-conf
      {{- if .Values.sapor.config.spinnaker.x509.enabled }}
      - name: certs-x509-volume
        configMap:
          name: oes-sapor-x509-config
      {{- end -}}
{{- end -}}
