{{- if or (eq .Values.installationMode "OES-AP")  (eq .Values.installationMode "EASY") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oes
    component: sapor
{{ include "oes.standard-labels" . | indent 4 }}
  name: oes-sapor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oes
      component: sapor
  template:
    metadata:
      annotations:
        configmap/checksum: {{ (.Files.Glob "config/oes-sapor/application.yml").AsConfig | sha256sum }}
{{- if .Values.sapor.annotations -}}
        {{ toYaml .Values.sapor.annotations | nindent 8 }}
{{- end }}
      labels:
        app: oes
        component: sapor
{{ include "oes.standard-labels" . | indent 8 }}
    spec:
      {{- if (eq .Values.db.enabled true) }}
      initContainers:
      - name: db-check
        image: {{ .Values.global.customImages.registry }}/postgres:9.6.5
        command: ['/bin/bash', '-c', "sleep 30;echo Waiting for oes-db to be up and running; pg_isready -h oes-db -p 5432 && echo PostgreSQL DB is ready to receive connections"]
      {{- end }}
      containers:
      - image: {{ template "sapor.image" . }}
        name: oes-sapor
        env:
       {{- if .Values.extraEnvVars }}
       {{- include "tplvalues.render" (dict "value" .Values.extraEnvVars "context" $) | nindent 8 }}
       {{- end }}
        ports:
        - containerPort: 8085
          protocol: TCP
        volumeMounts:
        {{- if .Values.forwarder.enabled }}
        - mountPath: /opt/opsmx/controller/ca.crt	
          name: ca-certs-volume	
          subPath: tls.crt	
        - mountPath: /opt/opsmx/controller/cert/tls.crt	
          name: certs-volume	
          subPath: tls.crt	
        - mountPath: /opt/opsmx/controller/cert/tls.key	
          name: certs-volume	
          subPath: tls.key
        {{- end }}
        - name: sapor-config-volume
          mountPath: /opt/opsmx/application.yml
          subPath: application.yml
        - mountPath: /opt/opsmx/bootstrap.yml
          name: bootstrap-config-volume
          subPath: bootstrap.yml
        {{- if .Values.global.customCerts.enabled }}
        - mountPath: /etc/pki/ca-trust/extracted/java/cacerts
          subPath: cacerts
          name: cacerts
        {{- end }}
        {{- if .Values.sapor.config.spinnaker.x509.enabled }}
        - name: certs-x509-volume
          mountPath: /opt/opsmx/client.p12
          subPath: client.p12
        {{- end }}
        resources:
{{ toYaml .Values.sapor.resources | indent 12 }}
        readinessProbe:
          tcpSocket:
            port: 8085
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /mgmt/health
            port: 8085
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 10
      {{- if .Values.imagePullSecret}}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret}}
      {{- end }}
      {{- if .Values.sapor.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.sapor.nodeSelector | indent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.forwarder.enabled }}
      - secret:
          secretName: oes-control-secret
        name: certs-volume
      - secret:
          secretName: ca-secret
        name: ca-certs-volume
      {{- end }}
      {{- if .Values.global.customCerts.enabled }}
      - name: cacerts
        secret:
          secretName: {{ .Values.global.customCerts.secretName }}
          items:
          - key: cacerts
            path: cacerts
      {{- end }}
      - secret:
          secretName: oes-sapor-config
        name: sapor-config-volume
      - secret:
          items:
          - key: bootstrap.yml
            path: bootstrap.yml
          secretName: sapor-bootstrap
        name: bootstrap-config-volume
      {{- if .Values.sapor.config.spinnaker.x509.enabled }}
      - name: certs-x509-volume
        configMap:
          name: oes-sapor-x509-config
      {{- end -}}
{{- end -}}
