{{- if or (eq .Values.installationMode "OES-AP") (eq .Values.installationMode "AP") (eq .Values.installationMode "OES") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: oes
    component: platform
{{ include "oes.standard-labels" . | indent 4 }}
  name: oes-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oes
      component: platform
  strategy: {}
  template:
    metadata:
      annotations:
        configmap/checksum: {{ (.Files.Glob "config/oes-platform/platform-local.yml").AsConfig | sha256sum }}
      labels:
        app: oes
        component: platform
{{ include "oes.standard-labels" . | indent 8 }}
    spec:
      initContainers:
      - name: db-check
        image: postgres:9.6.5
        command: ['/bin/bash', '-c', "sleep 30;echo Waiting for oes-db to be up and running; pg_isready -h oes-db -p 5432 && echo PostgreSQL DB is ready to receive connections"]
      containers:
      - image: {{ template "platform.image" . }}
        name: oes-platform
        ports:
        - containerPort: 8095
          protocol: TCP
        env:
        resources:
{{ toYaml .Values.platform.resources | indent 12 }}
        readinessProbe:
          tcpSocket:
            port: 8095
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /mgmt/health
            port: 8095
          initialDelaySeconds: 60
          periodSeconds: 60
        volumeMounts:
        - mountPath: /opsmx/conf/platform-local.yml
          name: platform-config-volume
          subPath: platform-local.yml
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      volumes:
      - name: platform-config-volume
        configMap:
          name: oes-platform-config
{{- end -}}
