{{- if or (eq .Values.installationMode "OES-AP")  (eq .Values.installationMode "EASY") -}}
{{- if .Values.opa.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: opa
{{ include "oes.standard-labels" . | indent 4 }}
  name: opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
{{ include "oes.standard-labels" . | indent 8 }}
      name: opa
    spec:
      containers:
        - name: opa
          image: {{ .Values.opa.image.repository }}:{{ .Values.opa.image.tag }}
          args:
            - "run"
            - "--server"
        - name: opa-persist
          command: 
          - /bin/bash
          - /tmp/config/opa-persist.sh
          envFrom:
          - secretRef:
              name: oes-gate-secret
          image: quay.io/opsmxpublic/customterraformstage:v1
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /tmp/config
            name: opa-persist
      {{- if .Values.imagePullSecret}}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret}}
      {{- end }}
      {{- if .Values.opa.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.opa.nodeSelector | indent 8 }}
      {{- end }}
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 420
            name: opa-persist
          name: opa-persist
{{- end -}}
{{- end -}}
