---
# Source: oes/templates/services/oes-visibility-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oes
    component: visibility 
    heritage: "Helm"
    release: "isd"
    chart: "oes-3.12.1"
  name: oes-visibility
spec:
  type: ClusterIP
  ports:
  - name: visibility 
    protocol: TCP
    port: 8096
    targetPort: 8096
  selector:
    app: oes
    component: visibility
