{{ if .Values.global.gitea.enabled }}
{{- if (eq .Values.global.gitea.admin.existingSecret "gitea-secret") }}
apiVersion: v1
stringData:
  # Repo uri to fetch halyard configuration
  username: {{ .Values.global.gitea.admin.username }}
  password: {{ .Values.global.gitea.admin.password }}
kind: Secret
metadata:
  name: {{ .Values.global.gitea.admin.existingSecret }}
type: Opaque
{{- end }}
{{ end }}
