{{- if or (eq .Values.installationMode "OES-AP")  (eq .Values.installationMode "EASY") -}}
apiVersion: v1
stringData:
  autopilot.properties: |
    {{- tpl (.Files.Get "config/oes-autopilot/autopilot.properties") . | nindent 4 }}
kind: Secret
metadata:
  name: oes-autopilot-config
  labels:
    app: oes
    component: autopilot
{{ include "oes.standard-labels" . | indent 4 }}
{{- end -}}
